// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncAPI.Data;

namespace SyncAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200312135707_CambioPrecisionDecimalesArticulo")]
    partial class CambioPrecisionDecimalesArticulo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SyncAPI.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoPereira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IDSyncIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Porcentaje10")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Porcentaje4")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Porcentaje5")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Porcentaje6")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Porcentaje7")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Porcentaje8")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Porcentaje9")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("PorcentajeMarcacion")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("PorcentajeMarcacionDos")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("PorcentajeMarcacionTres")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("Precio01")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio02")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio03")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio04")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio05")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio06")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio07")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio08")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio09")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Precio10")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PrecioUltimaCompra")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("IDSyncIdentifier");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SyncAPI.Models.SyncIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaFechaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SyncIdentifiers");
                });

            modelBuilder.Entity("SyncAPI.Models.Articulo", b =>
                {
                    b.HasOne("SyncAPI.Models.SyncIdentifier", "SyncIdentifier")
                        .WithMany("Articulos")
                        .HasForeignKey("IDSyncIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
